### PR TITLE
Fixed requester.getLocRateByCurrency in Service-Layer

### PR DESCRIPTION
**Pull request by alexyk**
Fixed requester.getLocRateByCurrency in Service-Layer.
Using Service-Layer from GitHub tag #1.0.55.

### CODE REVIEW

**Comment by Krastevo** [comment]
Keep up the good work!

**Comment by meshungina** [comment]
> Keep up the good work!

what does krastevo mean?

**Comment by smisel** [comment]
Може би е написал погрешно. странно.

**Comment by bromhexine** [comment]
> Може би е написал погрешно. странно.
Hi team does this fix hotel mapper issues?

**Comment by djdelmar** [comment]
Great job team. You inspire.

**Comment by thehappytoken** [comment]
Why all these comments?

**Pull request merged**
